RANK_LIMIT = 10
U_RECOMMEND_LIMIT = 10
L_RECOMMEND_LIMIT = 20
SEARCH_LIMIT = 10
RECOMMEND_LIMIT = 20
SHOWPOSTS_LIMIT = 10

DIALECT = 'mysql'
DRIVER = 'pymysql'
USERNAME = 'root'
PASSWORD = 'Zl25817029'
HOST = '114.116.242.168'
PORT = '3306'
DATABASE = 'stack'

SQLALCHEMY_DATABASE_URI = '{}+{}://{}:{}@{}:{}/{}?charset=utf8mb4'.format(
    DIALECT, DRIVER, USERNAME, PASSWORD, HOST, PORT, DATABASE
)
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_POOL_SIZE = 10
SQLALCHEMY_MAX_OVERFLOW = 5

DEBUG = False
PORT = 5000
HOST = "localhost"